# Taller Práctico: Manipulación de Datos con NumPy y Pandas
## Actividad 1: Explorando el Poder de NumPy (Arrays)
### **Objetivo Específico**: Familiarizarse con la creación, atributos, indexación, slicing y operaciones fundamentales de los arrays de NumPy

**1. Creación y Atributos de Arrays**
- Crea un array 1D llamado mediciones_flujo a partir de la siguiente lista de Python, que simula mediciones de flujo sanguíneo (en ml/s): [12.5, 13.2, 11.9, 14.0, 13.5, 12.8, 15.1, 13.0].


In [20]:
#instalo e importo librerias
#%pip install numpy
#%pip install pandas
import numpy as np
import pandas as pd

In [21]:
#creo un array de numpy con los datos de flujo sanguíneo
mediciones_flujo_list = [12.5, 13.2, 11.9, 14.0, 13.5, 12.8, 15.1, 13.0]
mediciones_flujo = np.array(mediciones_flujo_list)
print("mediciones_flujo:", mediciones_flujo)

mediciones_flujo: [12.5 13.2 11.9 14.  13.5 12.8 15.1 13. ]


- Crea un array 2D (matriz) llamado datos_pacientes_basicos a partir de la
siguiente lista de listas, donde cada fila representa [Edad, NivelColesterol,
PresionSistolica]: [[55, 220, 140], [62, 250, 155], [48, 190, 130], [59, 235,
148]].

In [22]:
#creo una matriz con datos de pacientes a partir de listas
datos_pacientes_basicos_list = [[55, 220, 140], [62, 250, 155], [48, 190, 130], [59, 235, 148]]
datos_pacientes_basicos = np.array(datos_pacientes_basicos_list)
print("datos_pacientes_basicos:\n", datos_pacientes_basicos)

datos_pacientes_basicos:
 [[ 55 220 140]
 [ 62 250 155]
 [ 48 190 130]
 [ 59 235 148]]


- Utiliza np.arange() para crear un array llamado secuencia_tiempo que represente puntos de tiempo desde 0 hasta 10 segundos, con incrementos de 0.5 segundos.

In [23]:
#Crea un array con puntos de tiempo de 0 a 10 segundos
secuencia_tiempo = np.arange(0, 10.5, 0.5)
print("secuencia_tiempo:", secuencia_tiempo)

secuencia_tiempo: [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


- Crea un array 1D llamado errores_simulados de 1000 elementos con valores aleatorios muestreados de una distribucion normal estandar (media 0, desviacion estandar 1) usando np.random.randn().

In [24]:
#Crea un array de 1000 elementos con valores aleatorios de una distribución normal con media 0 y desviación estándar 1
errores_simulados = np.random.randn(1000)
print("errores_simulados:", errores_simulados[:10])

errores_simulados: [-1.51229541 -0.94604291  0.23574991  1.12329207  0.79223151 -0.12762824
  0.45210156  0.24570514  0.42147851  1.29189281]


- Para cada uno de los arrays creados (mediciones_flujo, datos_pacientes_basicos, secuencia_tiempo,errores_simulados), imprime su forma (.shape), numero de dimensiones (.ndim), tamaño total (.size) y tipo de dato (.dtype).


In [25]:
arrays_creados = {
    "mediciones_flujo": mediciones_flujo,
    "datos_pacientes_basicos": datos_pacientes_basicos,
    "secuencia_tiempo": secuencia_tiempo,
    "errores_simulados": errores_simulados
}

print("Atributos de los arrays:")
for name, arr in arrays_creados.items():
    print(f"\nArray: {name}")
    print(f"Forma (.shape): {arr.shape}")
    print(f"Número de dimensiones (.ndim): {arr.ndim}")
    print(f"Tamaño total (.size): {arr.size}")
    print(f"Tipo de dato (.dtype): {arr.dtype}")

Atributos de los arrays:

Array: mediciones_flujo
Forma (.shape): (8,)
Número de dimensiones (.ndim): 1
Tamaño total (.size): 8
Tipo de dato (.dtype): float64

Array: datos_pacientes_basicos
Forma (.shape): (4, 3)
Número de dimensiones (.ndim): 2
Tamaño total (.size): 12
Tipo de dato (.dtype): int64

Array: secuencia_tiempo
Forma (.shape): (21,)
Número de dimensiones (.ndim): 1
Tamaño total (.size): 21
Tipo de dato (.dtype): float64

Array: errores_simulados
Forma (.shape): (1000,)
Número de dimensiones (.ndim): 1
Tamaño total (.size): 1000
Tipo de dato (.dtype): float64


**2. Indexación y Slicing**

- Usando datos_pacientes_basicos:
    - Selecciona e imprime la edad del segundo paciente.
    - Selecciona e imprime todos los datos del tercer paciente (la fila completa).
    - Selecciona e imprime solo la columna de NivelColesterol para todos los pacientes.
    - Selecciona e imprime un subconjunto que contenga la Edad y NivelColesterol de los primeros dos pacientes.

In [26]:
#Selecciona e imprime la edad del segundo paciente
edad_segundo_paciente = datos_pacientes_basicos[1, 0]
print(f"Edad del segundo paciente: {edad_segundo_paciente}")

Edad del segundo paciente: 62


In [27]:
#Selecciona e imprime todos los datos del tercer paciente
datos_tercer_paciente = datos_pacientes_basicos[2, :]
print(f"Datos del tercer paciente: {datos_tercer_paciente}")

Datos del tercer paciente: [ 48 190 130]


In [28]:
#Selecciona e imprime solo la columna de NivelColesterol para todos los pacientes   
nivel_colesterol = datos_pacientes_basicos[:, 1]
print(f"Nivel de colesterol de todos los pacientes: {nivel_colesterol}")

Nivel de colesterol de todos los pacientes: [220 250 190 235]


In [29]:
#Selecciona  e imprime un subconjunto que contenga la edad y NivelColesterol de los primeros dos pacientes
subconjunto_pacientes = datos_pacientes_basicos[:2, [0, 1]]
print(f"Subconjunto de edad y colesterol de los primeros dos pacientes:\n{subconjunto_pacientes}")

Subconjunto de edad y colesterol de los primeros dos pacientes:
[[ 55 220]
 [ 62 250]]


- Usando errores_simulados
    - Selecciona e imprimer los primeros 10 valores
    - Crea un nuevo array llamado errores_positivos que contenga solo los valores de errore_simulados que son mayores que 0. Imprime la cantidad de errores positivos encontrados

In [30]:
#10 primeros valores de errores_simulados
print(f"Primeros 10 valores de errores_simulados:\n{errores_simulados[:10]}")

Primeros 10 valores de errores_simulados:
[-1.51229541 -0.94604291  0.23574991  1.12329207  0.79223151 -0.12762824
  0.45210156  0.24570514  0.42147851  1.29189281]


In [31]:
#nuevo array con errores positivos y cantidad de errores positivos encontrados
errores_positivos = errores_simulados[errores_simulados > 0]
cantidad_errores_positivos = errores_positivos.size
print(f"Errores positivos:\n{errores_positivos[:10]}")
print(f"Cantidad de errores positivos encontrados: {cantidad_errores_positivos}")

Errores positivos:
[0.23574991 1.12329207 0.79223151 0.45210156 0.24570514 0.42147851
 1.29189281 0.09573727 0.48184679 1.59516563]
Cantidad de errores positivos encontrados: 485


**3. Operaciones y Estadísticas**
- Crea dos arrays 1D, vector_a = np.array([1, 5, 10, 15]) y vector_b = np.array([2, 4, 6, 8]). Realiza y muestra los resultados de:
    - Suma (vector_a + vector_b)
    - Multiplicacion elemento a elemento (vector_a * vector_b)
    - vector_a elevado al cuadrado.

In [32]:
#Creo los arrays de 1 dimension
vector_a = np.array([1, 5, 10, 15])
vector_b = np.array([2, 4, 6, 8])

In [33]:
#Suma de los vectores
suma_vectores = vector_a + vector_b
print(f"Suma de los vectores:\n{vector_a} + {vector_b} = {suma_vectores}")

Suma de los vectores:
[ 1  5 10 15] + [2 4 6 8] = [ 3  9 16 23]


In [34]:
#Multiplicación elemento a elemento
multiplicacion_vectores = vector_a * vector_b
print(f"Multiplicación elemento a elemento:\n{vector_a} * {vector_b} = {multiplicacion_vectores}")

Multiplicación elemento a elemento:
[ 1  5 10 15] * [2 4 6 8] = [  2  20  60 120]


In [35]:
#vector_a elevado al cuadrado
vector_a_cuadrado = vector_a ** 2
print(f"Vector_a elevado al cuadrado:\n{vector_a} ** 2 = {vector_a_cuadrado}")

Vector_a elevado al cuadrado:
[ 1  5 10 15] ** 2 = [  1  25 100 225]


- Toma la matriz datos_pacientes_basicos y suma un valor constante de 5 a la columna de PresionSistolica utilizando broadcasting (primero selecciona la columna, suma 5, y luego considera como reasignarla o crear una nueva matriz).


In [36]:
#Sumar un valor constante a la columna de PresionSistolica utilizando broadcasting
print("Matriz original datos_pacientes_basicos:")
print(datos_pacientes_basicos)

# Seleccionamos la columna y sumamos 5. NumPy maneja el broadcasting automáticamente.
datos_pacientes_basicos_modificado = datos_pacientes_basicos.copy()
datos_pacientes_basicos_modificado[1:, 2] += 5
print("datos_pacientes_basicos con 5 sumado a PresionSistolica:\n", datos_pacientes_basicos_modificado)

Matriz original datos_pacientes_basicos:
[[ 55 220 140]
 [ 62 250 155]
 [ 48 190 130]
 [ 59 235 148]]
datos_pacientes_basicos con 5 sumado a PresionSistolica:
 [[ 55 220 140]
 [ 62 250 160]
 [ 48 190 135]
 [ 59 235 153]]


- Para el array mediciones_flujo, calcula e imprime: la media, la mediana, la desviacion estandar, el valor mínimo y el máximo.


In [37]:
#estadísticos de mediciones_flujo
print("Estadísticos de mediciones_flujo:")
print(f"Media: {np.mean(mediciones_flujo)}")
print(f"Mediana: {np.median(mediciones_flujo)}")
print(f"Desviación estándar: {np.std(mediciones_flujo)}")
print(f"Valor mínimo: {np.min(mediciones_flujo)}")
print(f"Valor máximo: {np.max(mediciones_flujo)}")

Estadísticos de mediciones_flujo:
Media: 13.25
Mediana: 13.1
Desviación estándar: 0.9151502608861561
Valor mínimo: 11.9
Valor máximo: 15.1


- Para la matriz datos_pacientes_basicos, calcula e imprime la media de cada variable (cada columna) utilizando el parámetro axis.

In [38]:
#media de cada variable en datos_pacientes_basicos utilizando axis
print("Media de cada variable en datos_pacientes_basicos:")
media_por_columna = np.mean(datos_pacientes_basicos, axis=0)
print("(Orden: Edad, NivelColesterol, PresionSistolica)")
print(media_por_columna)


Media de cada variable en datos_pacientes_basicos:
(Orden: Edad, NivelColesterol, PresionSistolica)
[ 56.   223.75 143.25]


### **Comentario Actividad 1**
La actividad 1 ha permitido revisar conceptos estudiados en clase, con los que se pudo cubrir aspectos esenciales como: 
- Creación y manipulación de arrays: siendo unidimensionales y bidimensionales, así como el uso de funciones de numpy como arange, random, shape, ndim, size, dtype.
- Indexación y slicing: nos ha permitido familiarizarnos con la sintaxis de numpy para acceso y extracción de subconjuntos de datos.
- Operaciones y estadísticas: se ha podido revisar operaciones con vectores como: sumas, multiplicaciones y potencias. También la utilización del broadcasting para operaciones sobre subconjuntos de arrays y finalmente, el cálculo de estadísticos descriptivos básicos para obtener un resumen rápido de los datos.

## Actividad 2: Fundamentos de Pandas: Series y DataFrames
### Objetivo Específico: Practicar la creacion, inspeccion, seleccion, filtrado y operaciones básicas con Series y DataFrames de Pandas.

**1. Trabajando con Series:**

In [39]:
#a. Crea una Serie de Pandas llamada puntuaciones_asignatura con las siguientes puntuaciones
puntuaciones_asignatura=pd.Series([7.5, 8.0, 9.5, 6.0, 7.0, 8.8],
    index=['Ana', 'Luis', 'Eva', 'Juan', 'Sara', 'Pedro'])

In [40]:
#b. Imprime la puntuacion de 'Eva'.
print("Puntuación de Eva:", puntuaciones_asignatura['Eva'])

Puntuación de Eva: 9.5


In [41]:
# c. Imprimir puntuaciones de 'Luis', 'Juan' y 'Pedro'
print("Puntuaciones de Luis, Juan y Pedro:")
puntuaciones_asignatura[['Luis', 'Juan', 'Pedro']]

Puntuaciones de Luis, Juan y Pedro:


Luis     8.0
Juan     6.0
Pedro    8.8
dtype: float64

In [42]:
# d. Puntuaciones mayores o iguales a 8.0
print("Puntuaciones >= 8.0:")
print(puntuaciones_asignatura[puntuaciones_asignatura >= 8.0])

Puntuaciones >= 8.0:
Luis     8.0
Eva      9.5
Pedro    8.8
dtype: float64


In [43]:
# e. Aumentar en 0.5 puntos todas las puntuaciones
puntuaciones_aumentadas = puntuaciones_asignatura + 0.5
print("Puntuaciones con +0.5:")
print(puntuaciones_aumentadas)

Puntuaciones con +0.5:
Ana       8.0
Luis      8.5
Eva      10.0
Juan      6.5
Sara      7.5
Pedro     9.3
dtype: float64


**2. Creación e Inspección de DataFrames:**

In [44]:
#a. Crea un DataFrame llamado df_estudiantes a partir del siguiente diccionario Python:
datos_estudiantes = {
    'ID_Estudiante': ['E001', 'E002', 'E003', 'E004', 'E005'],
    'Nombre': ['Carlos', 'Laura', 'Miguel', 'Sofia', 'David'],
    'Edad': [28, 32, 29, 35, 31],
    'Programa': ['Estadística', 'Ciencia de Datos', 'IA', 'Estadística', 'Ciencia de Datos'],
    'Semestre': [3, 2, 4, 3, 2]
}
df_estudiantes = pd.DataFrame(datos_estudiantes)

In [45]:
#b. Muestra las primeras 3 filas de df_estudiantes.
print("Primeras 3 filas:")
df_estudiantes.head(3)

Primeras 3 filas:


ID_Estudiante  Nombre  Edad          Programa  Semestre
0          E001  Carlos    28       Estadística         3
1          E002   Laura    32  Ciencia de Datos         2
2          E003  Miguel    29                IA         4

In [46]:
# c. Muestra un resumen conciso de df_estudiantes usando .info().
print("Resumen con info():")
print(df_estudiantes.info())

Resumen con info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   ID_Estudiante  5 non-null      object
 1   Nombre         5 non-null      object
 2   Edad           5 non-null      int64 
 3   Programa       5 non-null      object
 4   Semestre       5 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes
None


In [47]:
# d. Obten y muestra las estadísticas descriptivas para las columnas nume ricas de df_estudiantes usando .describe().
print("Estadísticas descriptivas:")
print(df_estudiantes.describe())

Estadísticas descriptivas:
            Edad  Semestre
count   5.000000   5.00000
mean   31.000000   2.80000
std     2.738613   0.83666
min    28.000000   2.00000
25%    29.000000   2.00000
50%    31.000000   3.00000
75%    32.000000   3.00000
max    35.000000   4.00000


In [48]:
# e. Imprime la forma (shape) y los tipos de datos (dtypes) del DataFrame.
print("Forma del DataFrame:", df_estudiantes.shape)
print("Tipos de datos:")
df_estudiantes.dtypes

Forma del DataFrame: (5, 5)
Tipos de datos:


ID_Estudiante    object
Nombre           object
Edad              int64
Programa         object
Semestre          int64
dtype: object

**3. Selección y Filtrado en DataFrames:**

In [49]:
#a. Selecciona e imprime solo la columna Nombre y Programa.
print("Columnas Nombre y Programa:")
df_estudiantes[['Nombre', 'Programa']]

Columnas Nombre y Programa:


Nombre          Programa
0  Carlos       Estadística
1   Laura  Ciencia de Datos
2  Miguel                IA
3   Sofia       Estadística
4   David  Ciencia de Datos

In [50]:
# b. Selecciona e imprime los datos del estudiante con ID_Estudiante 'E003' utilizando .loc[]
df_estudiantes.set_index('ID_Estudiante', inplace=True)
print("Datos del estudiante con ID 'E003':")
print(df_estudiantes.loc['E003'])

Datos del estudiante con ID 'E003':
Nombre      Miguel
Edad            29
Programa        IA
Semestre         4
Name: E003, dtype: object


In [51]:
# c. Selecciona e imprime la segunda y tercera fila del DataFrame utilizando .iloc[]
print("Segunda y tercera fila:")
df_estudiantes.iloc[1:3]

Segunda y tercera fila:


Nombre  Edad          Programa  Semestre
ID_Estudiante                                          
E002            Laura    32  Ciencia de Datos         2
E003           Miguel    29                IA         4

In [52]:
# d. Selecciona e imprime el Nombre y Edad de los estudiantes que estan en el Semestre 2.
print("Nombre y Edad de estudiantes en Semestre 2:")
df_estudiantes[df_estudiantes['Semestre'] == 2][['Nombre', 'Edad']]

Nombre y Edad de estudiantes en Semestre 2:


Nombre  Edad
ID_Estudiante             
E002           Laura    32
E005           David    31

In [53]:
# e. Filtra el DataFrame para mostrar solo los estudiantes que esta n en el programa de 'Ciencia de Datos' Y tienen una Edad mayor a 30 anos
print("Estudiantes en Ciencia de Datos con Edad > 30:")
df_estudiantes[
    (df_estudiantes['Programa'] == 'Ciencia de Datos') &
    (df_estudiantes['Edad'] > 30)
]

Estudiantes en Ciencia de Datos con Edad > 30:


Nombre  Edad          Programa  Semestre
ID_Estudiante                                         
E002           Laura    32  Ciencia de Datos         2
E005           David    31  Ciencia de Datos         2

**4. Operaciones Básicas y Agregación Simple:**

In [54]:
#a. Anade una nueva columna al df_estudiantes llamada Edad_Meses que sea la Edad multiplicada por 12.
df_estudiantes['Edad_Meses'] = df_estudiantes['Edad'] * 12
print("DataFrame con Edad_Meses:")
df_estudiantes

DataFrame con Edad_Meses:


Nombre  Edad          Programa  Semestre  Edad_Meses
ID_Estudiante                                                      
E001           Carlos    28       Estadística         3         336
E002            Laura    32  Ciencia de Datos         2         384
E003           Miguel    29                IA         4         348
E004            Sofia    35       Estadística         3         420
E005            David    31  Ciencia de Datos         2         372

In [55]:
# b. Calcula e imprime la edad promedio de los estudiantes.
edad_promedio = df_estudiantes['Edad'].mean()
print("Edad promedio de estudiantes:", edad_promedio)

Edad promedio de estudiantes: 31.0


In [56]:
# c. Agrupa los datos por Programa y calcula la edad promedio y el semestre promedio para cada programa.
agrupado = df_estudiantes.groupby('Programa').agg({
    'Edad': 'mean',
    'Semestre': 'mean'
})
print("Promedios por Programa:")
agrupado

Promedios por Programa:


Edad  Semestre
Programa                        
Ciencia de Datos  31.5       2.0
Estadística       31.5       3.0
IA                29.0       4.0